[SETUP][#9] - config env variables
GuilhermeABRoncari/cinemenu-api pull request #15
Opened 2023-05-11 22:08 UTC by GuilhermeABRoncari

Adding sensitive files in Gitignore, to protect sigilous informations.
Fixes #9

2023-05-12 01:43 UTC, ThiagoSousaSantana commented on .gitignore
> +/src/main/resources/application.properties
Colocar o application.properties no gitignore não é uma boa ideia.

Você pode usar variaveis de ambiente para esconder as informações confidenciais:
`uri: ${MONGO_DATABASE_URI:mongodb://localhost:27017}`

Na configuração acima a uri sera substituida por uma variavel de ambiente se ela existir. Se não existir vai usar a uri que esta depois dos dois pontos

2023-05-12 01:43 UTC, ThiagoSousaSantana commented on .gitignore
> +/src/main/resources/application.properties
Um pouco mais sobre esse tipo de configuração
https://blog.devgenius.io/working-with-application-properties-in-spring-boot-79e72630bba0

2023-05-12 02:42 UTC, GuilhermeABRoncari commented
Eu tive de criar um DB pra fazer essas variaveis de ambiente e testa-las, então eu tive de pular ums passos das issues que seriam criadas.

2023-05-14 02:45 UTC, amanda-a-reis commented
Eu não sou entendedora de Java/Spring, porém, oq se imagina em geral, com relação às variáveis de ambiente, é _esconder_ os valores e deixá-los disponíveis em determinado contexto, que pode ser local, por exemplo.

No entanto, aqui nas actions, quando formos testar e2e (ir até o endpoint, realizar ação no banco, retornar a resposta), vamos precisar passar esses valores para o CI, eles ficam salvos nas secrets do GitHub, e sem esses valores, o CI vai quebrar.

Exemplo do projeto antigo

_Nos testes, eu adicionei essa variável genérica ENV_NUMBER para simular um valor real._

```yml
 - name: Run tests
        run: npm run test:all
        env:
          ENV_NUMBER: ${{ secrets.ENV_NUMBER }}
```

Além disso, essas variáveis podem mudar de acordo com o ambiente (**desenvolvimento, produção, local, testes**).
___

Em um projeto com Typescript (que era a tecnologia que nós estavamos usando antes), nós usávamos essas variáveis localmente,  em um arquivo .env

```bash
# .env
ENV_NUMBER=10
```

Assim, o que era colocado no .gitignore, era o arquivo específico .env, simplesmente para que ele não fosse comitado.

___

#### Esse tema é muito importante para o bom funcionamento e segurança do código, seria interessante conversarmos para descobrir como fazer da melhor maneira no Spring.

2023-05-14 02:46 UTC, amanda-a-reis commented
> Eu tive de criar um DB pra fazer essas variaveis de ambiente e testa-las, então eu tive de pular ums passos das issues que seriam criadas.

Não precisava na verdade, bastaria criar um valor genérico ali e tentar recuperá-lo no código. Isso já indicaria que você conseguiu usar a variável.

2023-05-15 00:51 UTC, NewtonCesarRoncari requested changes
Manter tambem application.properties padrão com valores padrões

2023-05-15 09:52 UTC, NewtonCesarRoncari approved these changes

2023-05-15 09:53 UTC, merged