[FEATURE][#25] - Search by genre
GuilhermeABRoncari/cinemenu-api pull request #26
Opened 2023-06-15 02:21 UTC by GuilhermeABRoncari

Create a new endpoint to return a list of tv series simultaneous to movies by genres converting the cine-menu internal genre IDs to TMBD genre IDs randomly.

2023-06-20 02:00 UTC, NewtonCesarRoncari requested changes

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
> +        if (page < 1 || page > 500) throw new InvalidSearchException("search page cannot be less then 1 or more than 500");
Externalizar a palavra e a quantidade **500** para uma constante, assim se mudarmos no futuro não precisa sair alterando em todos os métodos

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/mapper/TMDBInternalGenreMapper.java
> +public class TMDBInternalGenreMapper {
Acredito que daria pra alterar essa classe para um map de chave e valor, no qual a chave de um genero corresponde ao valor do outro genero 
algo mais ou menos assim 

```public class TMDBInternalGenreMapper {
    private static final Map<CineMenuGenres, Integer> genreIdMap = createGenreIdMap();

    private static Map<CineMenuGenres, Integer> createGenreIdMap() {
        Map<CineMenuGenres, Integer> map = new HashMap<>();
        map.put(CineMenuGenres.ACTION, 28);
        map.put(CineMenuGenres.ADVENTURE, 12);
        map.put(CineMenuGenres.ANIMATION, 16);
       // ... os outros generos
        return map;
    }

    public static List<Integer> mapToMovieIds(List<CineMenuGenres> genres) {
        return mapToIds(genres);
    }

    public static List<Integer> mapToTvShowIds(List<CineMenuGenres> genres) {
        return mapToIds(genres);
    }

    private static List<Integer> mapToIds(List<CineMenuGenres> genres) {
        List<Integer> genreIds = new ArrayList<>();

        for (CineMenuGenres genre : genres) {
            Integer genreId = genreIdMap.get(genre);
            if (genreId != null) {
                genreIds.add(genreId);
            }
        }

        return genreIds;
    }
}```

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
>          if (page < 1 || page > 1000) throw new InvalidSearchException("search page cannot be less then 1 or more than 1000");
Externalizar a palavra e a quantidade 500 para uma constante, assim se mudarmos no futuro não precisa sair alterando em todos os métodos, a API do TMDB só aceita até a paginação 500

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
> +            Thread.sleep(500); // Atraso de 0.5 segundo (500 milissegundos)
Acredito que `Thread.sleep(500);`  nunca é uma abordagem interessante, ha não ser que esteja testando algo, não funciona sem esse código ?, se não funcionar acredito que teremos de achar outra alternativa

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/domain/enumeration/CineMenuGenresTest.java
> +        int genreId = 999; // Invalid genre ID
Basta alterar o nome da variável de `genreId` para `invalidGenreId` assim não precisa do comentário

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/domain/enumeration/CineMenuGenresTest.java
> +        int genreId = 32; // Comedy
Basta alterar o nome da variável de `genreId` para `comedyGenreId` assim não precisa do comentário

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/rest/controller/CineMenuPreviewMediaControllerTest.java
> +        assertEquals(listResponseEntity.getStatusCodeValue(),ResponseEntity.ok(listResponseEntity.getBody()).getStatusCodeValue());
Neste teste está faltando os comentários `//Given` `//When` e `//Then`

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepositoryTest.java
> +    @DisplayName("When valid request is performed, it should return the PreviewMediaResponsePage")
Este testes e os próximos estão faltando os comentários de `//Given` `//When` e `Then`

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/rest/service/PreviewMediaServiceTest.java
> +//                .anyMatch(media -> media.media_type().equals(MediaType.PERSON.name().toLowerCase())));
Código comentado, ou descomentar, ou descartar

2023-06-20 02:00 UTC, NewtonCesarRoncari commented on src/test/java/br/com/cinemenu/cinemenuapi/rest/service/PreviewMediaServiceTest.java
> +//                .anyMatch(media -> !media.media_type().equals(MediaType.PERSON.name().toLowerCase())));
Código comentado, ou descomentar, ou descartar

2023-06-20 02:16 UTC, NewtonCesarRoncari requested changes

2023-06-20 02:16 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/domain/enumeration/CineMenuGenres.java
> +    private int cineMenuGenreId;
Esta variável pode ser final

2023-06-22 01:08 UTC, NewtonCesarRoncari requested changes

2023-06-22 01:08 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/mapper/TMDBInternalGenreMapper.java
> +    }
aparentemente estes 2 métodos estão fazendo a mesma coisa só muda o genreIdMap, não seria interessante criar um método só que recebe genres e genreIdMap por parametro ?

2023-06-22 01:08 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/domain/enumeration/CineMenuGenres.java
> +        throw new IllegalArgumentException("Invalid CineMenuGenre ID: " + cineMenuGenreId);
Trocar a mensagem `Invalid CineMenuGenre ID:` para `Invalid genre id`

2023-06-22 01:08 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
> +        if (page < 1 || page > MAX_PAGES) throw new InvalidSearchException("search page cannot be less then 1 or more than 1000");
A mensagem em String ainda referencia como se fossem 1000 páginas, colocar a constante dentro da mensagem pode solucionar a situação e auxiliar na abstraçã

2023-06-22 01:08 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
> +        if (totalPages > 500) totalPages = 500;
trocar 500 por MAX_PAGES

2023-06-22 01:08 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/repository/PreviewMediaRepository.java
> +        if (page < 1 || page > MAX_PAGES) throw new InvalidSearchException("search page cannot be less then 1 or more than 500");
Inserir a constante `MAX_PAGES` no lugar de 500 dentro da String

2023-06-22 01:12 UTC, GuilhermeABRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/mapper/TMDBInternalGenreMapper.java
> +    }
Eu tive de separar os dois, por que se vai um ID que só pertence a filmes no request para api do TMDB que busca por series vou ter um erro como resposta, e o mesmo ocorre no caso oposto, então tenho que ter certeza de que para o Request de filmes, só vá IDs que existem no endpoint de filmes, e o mesmo para series! Se eu fizesse em um único método, as IDs se misturariam e em quase todas as requisições seria recebido um erro como resposta.

2023-06-22 01:25 UTC, NewtonCesarRoncari commented on src/main/java/br/com/cinemenu/cinemenuapi/rest/mapper/TMDBInternalGenreMapper.java
> +    }
se receber por parametro o map, a lista vai rodar no map recebido, se passar o Map de TVs, vai retornar só o de TV se passar o map de Movies vai retornar só levando em conta o id dos Movies, seria algo assim 

```private static List<Integer> mapForIds(List<CineMenuGenres> genres, Map<CineMenuGenres, Integer> genreIdMap) {
    List<Integer> genreIds = new ArrayList<>();

    for (CineMenuGenres genre : genres) {
        Integer genreId = genreIdMap.get(genre);
        if (genreId != null) {
            genreIds.add(genreId);
        }
    }

    return genreIds;
}
```

2023-06-22 01:41 UTC, NewtonCesarRoncari approved these changes

2023-06-22 01:41 UTC, merged